version: "3.8"

services:
  fronthouse-git-server:
    image: dockerly/public-key-server
    container_name: public-key-server
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./certificates:/app/certificates
    restart: unless-stopped
